// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"IniciarVariaveis","status":true,"description":"Iniciar as variaveis que serão utilizadas nos calculos","parameters":{}},
{"name":"MathCombat","status":true,"description":"Substituição de opções de combate","parameters":{}}
];
