// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"IniciarVariaveis","status":true,"description":"Iniciar as variaveis que serão utilizadas nos calculos","parameters":{}}
];
